# ansible/playbook.yml

- name: Build and Run Project
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
      - ./vars/main.yml

  tasks:
      - name: Include Service Role
        include_role:
            name: '{{ type }}'
        when: type in ['nodejs', 'react']
